title: W3lc0me to my personal page
email: fanis.xeim[at]google.com
description: >- # this means to ignore newlines until "baseurl:"
  This page is created to share my CV, my interests and other technical info with anyone from the tech community.
show_downloads: true
google_analytics:
  google_analytics: G-YCKEN1MCQ8
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username: "0x66616e6973"
linkedin_username: theofanis-cheimariotis
# Build settings
#theme: jekyll-theme-clean-blog 
#remote_theme: pages-themes/startbootstrap-clean-blog-jekyll
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme 
#theme: jekyll-theme-hacker